version: '3.8'

services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python -u /src/app/db/init_db.py &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
    env_file: .env
    environment:
      - PYTHONPATH=/src
    depends_on:
      - db
      - redis
    networks:
      - backend
    ports:
      - 8000:8000

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "echo 'Starting Celery Worker...' &&
             celery -A app.core.celery_app worker --loglevel=info --concurrency=5"
    env_file: .env
    environment:
      - PYTHONPATH=/src
    depends_on:
      - db
      - redis
    networks:
      - backend

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "echo 'Starting Celery Beat...' &&
             celery -A app.core.celery_app beat --loglevel=info"
    env_file: .env
    environment:
      - PYTHONPATH=/src
    depends_on:
      - db
      - redis
    networks:
      - backend

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "echo 'Starting Flower...' &&
             celery -A app.core.celery_app flower --port=5555 --broker=$CELERY_BROKER_URL"
    env_file: .env
    environment:
      - PYTHONPATH=/src
    depends_on:
      - db
      - redis
      - celery_worker
      - celery_beat
    ports:
      - 5555:5555
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
